steps:
  # 1. Deploy the Cloud Function (as a private function)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - getAiSuggestions # The name of your function
      - --source=./cloud-function
      - --trigger-http
      - --runtime=nodejs18
      - --entry-point=getAiSuggestions
      - --region=us-central1
      - --set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}
    id: 'Deploy Cloud Function'

  # 2. Deploy ONLY the static website files to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'index.html'
      - 'script.js'
      - 'style.css'
      - 'assets'
      - 'gs://${_GCS_BUCKET_NAME}/'
    id: 'Deploy Static Assets'

substitutions:
  _GCS_BUCKET_NAME: 'your-gcs-bucket-name'
  _GEMINI_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY

