steps:
  # 1. Deploy the Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - getAiSuggestions # The name of your function
      - --source=./cloud-function
      - --trigger-http
      - --runtime=nodejs18
      - --allow-unauthenticated
      - --entry-point=getAiSuggestions
      - --region=us-central1 # You can change this to your preferred region
      - --set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}
    id: 'Deploy Cloud Function'

  # 2. Deploy ONLY the static website files to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'index.html'
      - 'script.js'
      - 'style.css'
      - 'assets'
      - 'gs://${_GCS_BUCKET_NAME}/' # Note the trailing slash
    id: 'Deploy Static Assets'

# You will set these variables in the Cloud Build Trigger settings
substitutions:
  _GCS_BUCKET_NAME: 'your-gcs-bucket-name' # Replace with your bucket name
  _GEMINI_API_KEY: '' # This will be populated from Secret Manager

